### PR TITLE
Support zero digit for exponents

### PR DESCRIPTION
**Pull request by ikhsan**
In regard to #61

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]
👍 from me on the grounds of maintaining compatibility.

**Comment by endocrimes** [comment]
@LoganWright - do you have any strong feelings either way on this before I merge?

**Comment by ikhsan** [comment]
@DanToml @LoganWright any update on this? Is there anything I can help or test?

**Comment by endocrimes** [comment]
@ikhsan I'll merge this now.

**Comment by ikhsan** [comment]
Thanks @DanToml!

**Comment by endocrimes** [comment]
@ikhsan I'll try and tag a release this week

**Comment by ikhsan** [comment]
thanks again, really appreciated it. quick question, after it's tagged, does that mean that vapor and [vapor/json](https://github.com/vapor/json) will automatically get that latest patch?

**Pull request merged**
