### PR TITLE
update travis and version for 3.0 release

### PR DESCRIPTION
**Pull request by loganwright**
Hey Dan,

Thanks for taking over for Honza 👍 , looking forward to parsing some more JSON. 

This PR is because 3.0 is officially out on Linux, and we're looking to stabilize our dependencies w/ this 1.0 as soon as we can.

Thanks,

Logan

### CODE REVIEW

**Comment by endocrimes** [comment]
Hey Logan,
Thanks for the PR!

Unfortunately I'd really rather not have us evaling curl output in tests where possible as this breaks usage of git bisect and to have repeatable builds throughout the history.

You are however welcome to submit a PR with the build scripts, but please break them out into the dependency and test steps, as this has much better support on CI.

**Comment by loganwright** [comment]
@DanToml Scripts are now committed in a `.travis` folder so they'll be tracked in history 👍

**Comment by endocrimes** [comment]
Great, thanks!

**Comment by loganwright** [comment]
Thanks for getting this in @DanToml! Sorry to keep pushing, but one more thing. Could we also get a 1.0.0 tag? That is the last thing blocking us from moving forward with out release 👍

**Pull request merged**
