### PR TITLE
Fix conversion of String->Int dictionary

### PR DESCRIPTION
**Pull request by remko**
Failing test for #52

### CODE REVIEW

**Comment by czechboy0** [comment]
Can you please also add the test of the name to the manifest so that this test is ran on Linux as well? https://github.com/DanToml/Jay/blob/master/Tests/JayTests/FormattingTests.swift#L34

**Comment by remko** [comment]
Oops, missed that. Fixed.

**Comment by remko** [comment]
I did an explicit typecheck on `Int`  instead of a cast. Let's see if the Linux builds still succeed.

Note that the inverse (typechecking for `Bool`) doesn't work; `someInt is Bool` returns `true`.

**Comment by remko** [comment]
Note to self: run the full unit test suite before pushing :( Sorry for the noise, back to the drawing board.

**Comment by remko** [comment]
Not sure why the build is failing; the tests seem to pass.

**Comment by remko** [comment]
Any updates on this? Is there anything I can do to get this merged?

**Review by endocrimes — APPROVED** [review]

**Comment by endocrimes** [comment]
Looks like this will need a rebase then it's good to go, sorry for the delay!

**Comment by remko** [comment]
@DanToml Thanks, done!

**Pull request merged**
