### PR TITLE
Compiles in Swift 3

### PR DESCRIPTION
**Pull request by jcampbell05**

### CODE REVIEW

**Comment by czechboy0** [comment]
Jay is now using the 07-25 toolchain, which works with Xcode 8 beta 3. The changes you made are back to the old way of doing things. Which Swift version are you looking to support? I'm sure there's an [older Jay release](https://github.com/czechboy0/Jay/releases) that supports it.

**Comment by jcampbell05** [comment]
@czechboy0 I'm using the one here https://github.com/swiftdocker/docker-swift/blob/master/Dockerfile

Is this the most up to date one.

**Comment by czechboy0** [comment]
It seems the Dockerfile is at least two Swift versions behind. The latest is `DEVELOPMENT-SNAPSHOT-2016-07-25-a`.

**Comment by jcampbell05** [comment]
@czechboy0  Many thanks, I shall update and PR to that one.

**Pull request closed without merging**
